// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7-dFrSGgS7rd0R1RqGBIXi-PpvtZkgw',
    appId: '1:890575672959:web:3c91a5dab6bf51a0c3514a',
    messagingSenderId: '890575672959',
    projectId: 'oko-auth-881ea',
    authDomain: 'oko-auth-881ea.firebaseapp.com',
    storageBucket: 'oko-auth-881ea.appspot.com',
    measurementId: 'G-H9GS1KFGHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_sT6NC6OQ5gSENePMgY80FbaWYJKeNmc',
    appId: '1:890575672959:android:9f9a497c7c35f4e1c3514a',
    messagingSenderId: '890575672959',
    projectId: 'oko-auth-881ea',
    storageBucket: 'oko-auth-881ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Xz6iaOuT6xRhH4M2ZyQ39-0LU4oIBHA',
    appId: '1:890575672959:ios:fbc163d093dee528c3514a',
    messagingSenderId: '890575672959',
    projectId: 'oko-auth-881ea',
    storageBucket: 'oko-auth-881ea.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Xz6iaOuT6xRhH4M2ZyQ39-0LU4oIBHA',
    appId: '1:890575672959:ios:fbc163d093dee528c3514a',
    messagingSenderId: '890575672959',
    projectId: 'oko-auth-881ea',
    storageBucket: 'oko-auth-881ea.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo7-dFrSGgS7rd0R1RqGBIXi-PpvtZkgw',
    appId: '1:890575672959:web:15dc6b56f79dfef6c3514a',
    messagingSenderId: '890575672959',
    projectId: 'oko-auth-881ea',
    authDomain: 'oko-auth-881ea.firebaseapp.com',
    storageBucket: 'oko-auth-881ea.appspot.com',
    measurementId: 'G-BF8R7VH08J',
  );
}
